version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Bootstrapper/Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: QuizServerDb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: quiz-server-postgres-data